### ISSUE TITLE
Porter archive restore not taking repository from tag - always pointing to docker.io

### ISSUE THREAD

**Issue by sajuptpm** [deislabs/porter#1055]
## Describe the bug
Porter archive restore not taking repository from tag - always pointing to docker.io

## To Reproduce
* use local registry
* porter publish -a bundle3.tgz --tag myregistry1.com/apache:v0.1.1

## Expected behavior
NA

## Porter Command and Output
```
# porter publish -a bundle3.tgz --tag myregistry1.com/apache:v0.1.1
Beginning bundle publish to myregistry1.com/apache:v0.1.1. This may take some time.
Error: unable to push image docker.io/apache/myregistry1.com/testapp-bundle2-installer:0.1.0: failed to write image sha256:d1a5b86c6992eff26f5d346a7d72968505ade43015bf5c7ba07adc82b3f0a448 to docker.io/apache/myregistry1.com/testapp-bundle2-installer:0.1.0: failed to write image docker.io/apache/myregistry1.com/testapp-bundle2-installer:0.1.0: unsupported status code 401
```

## Version
Copy the output of `porter version` below

[e.g. porter v0.14.1-beta.2 (72dd5df)]

**Comment by carolynvs** [comment]
Thanks for the bug report. I was wondering about this from your other logs. Something seemed different and yeah it looks like it is... you really are always really getting docker.io! 🤔 

So that I can reproduce this, the source image should be `localhost:5000/nginx` (where nginx is one of the images used in the bundle) and the destination bundle tag should be at a real resolvable domain without a port, e.g. `example.com/apache` (where apache is the name of the bundle, e.g. you ran the command `porter publish --tag example.com/apache:v0.1.0`).

I want to make sure I have the right setup since I am having trouble reproducing this so far, so let me know if that's not exactly what you are doing. Things like having an organization in between, e.g. `localhost:500/myorg/nginx` make a difference. The porter.yaml that you copied me the other day didn't use a local registry so I want to make sure I have it exactly right to reproduce it. 😀

**Comment by vdice** [comment]
I wasn't able to reproduce this with the latest Porter client:
```
 $ porter version
porter v0.26.2-beta.1-18-gc0dc3415 (c0dc3415)

 $ porter publish -a mybun.tgz -t localhost:5000/porter-terraform-keyvault-bundle:v0.1.0
Beginning bundle publish to localhost:5000/porter-terraform-keyvault-bundle:v0.1.0. This may take some time.
Starting to copy image localhost:5000/porter-terraform-keyvault-installer@sha256:9cc2e6efdcf0d334d602df4bac6e0068802e4667a1ea74cb139413e8c0251472...
Completed image localhost:5000/porter-terraform-keyvault-installer@sha256:9cc2e6efdcf0d334d602df4bac6e0068802e4667a1ea74cb139413e8c0251472 copy
Bundle tag localhost:5000/porter-terraform-keyvault-bundle:v0.1.0 pushed successfully, with digest "sha256:e1bb740b89d65e355fb728ecabb1b5346efeb0cf90017ab946da66921d16056d"
```
I believe publishing should now be in a solid state, what with recent fixes in this area, most recently in https://github.com/deislabs/porter/pull/1047.

@sajuptpm can you try again with the [latest Porter client](https://porter.sh/install/#canary) and see if the issue above is still being encountered?

**Comment by vdice** [comment]
I retested this with the latest client (`porter v0.27.1-6-g1534b89e (1534b89e)`) and again have failed to reproduce the issue.  Please feel free to re-open if there are cases where it's still being hit.  Thanks!
