### ISSUE TITLE
Error: bundle mysql not available locally or in /home/xxx/.porter

### ISSUE THREAD

**Issue by isurulucky** [deislabs/porter#108]
I have, 

1. used porter to create the mysql bundle.json
2. duffle to install it

When I try to build the wordpress porter.yaml which takes a dependency on mysql, it gives the error: 
`Error: bundle mysql not available locally or in /home/xxx/.porter`

I assume I have to somehow 'install' the mysql to /home/xxx/.porter to get the wordpress porter.yaml building. How can I do that?

**Comment by vdice** [comment]
@isurulucky I _believe_ you are hitting the issue fixed (or proposed to fix) in https://github.com/deislabs/porter/pull/104

I didn't explicitly mention the issue fixed in that PR (boils down to the `Name` property fix in `pkg/config/manifest.go`), but, currently, the `bundle.json` generated by `porter build` has an empty Name field.  Thus, if you were to list local bundles after the porter build, you would see an entry with no name, like so:
```
 $ duffle bundle list
NAME                        	VERSION                                 	DIGEST                                  	SIGNED?
                            	0.1.0                                   	9a404ed5bc50950d15ffd99daeb4222109e75eb5	true
```

This would be the bundle just built -- and since it is looking for the name you gave it, but which was dropped due to the bug, duffle/porter can't find the local bundle.

That's all assuming you are hitting what is described above.  Would it be possible to confirm via a `duffle bundle list`?  (And then, if so, perhaps taking a moment of your time to test the same workflow off of the fix PR?)  Thanks!

**Comment by isurulucky** [comment]
Thanks @vdice. Will try this and get back.
