### ISSUE TITLE
update porter icon

### ISSUE THREAD

**Issue by flynnduism** [deislabs/porter#198]
I've redrawn an icon that *hopefully* invokes a likeness of the emoji, but is drawn from scratch and w/ variations. In addition I've looked at some ways to tie this into the CNAB family a bit, mostly through colors that we may or may not like" 

![porter-gray](https://user-images.githubusercontent.com/686194/53522706-d6ccef80-3a8f-11e9-928f-f66c1a17cd7c.png)

^ Using the same typography as Duffle as a part of the family of projects.

![porter-cnab-gray](https://user-images.githubusercontent.com/686194/53522954-5bb80900-3a90-11e9-8528-33fd49f0de6b.png)

^  Bringing in some CNAB icons on the porters hat.

![porter-cnab-purple](https://user-images.githubusercontent.com/686194/53522985-70949c80-3a90-11e9-8f7e-3584b7a19b96.png)

^ Going full CNAB-purple.

**Comment by flynnduism** [comment]
I think their mouth / expression looks weird... and I also want to make the hair and skins tones closer to what we originally wanted. 

Will add an update for that - but wanted to throw out what's done so far for feedback because it's been taking so long.

**Comment by carolynvs** [comment]
@michelleN We need your input on the logo, since it is _you_ afterall. 😀 

I like the middle one the best since it incorporates the cnab logo. The one with the purple jacket is harder to see the logo, and kind of looses the porter-y feel from the original.

**Comment by carolynvs** [comment]
I forgot to say the first thing that came into my head "ahem"

💯  I LOVE IT!!! 🚀

**Comment by carolynvs** [comment]
I left this issue open so that @michelleN could provide feedback on the logo (or give it the 👍). I tweaked it a bit to soften the outline around the hat, and did change the logo on the docs page (#204) for now while we work out the final logo. Once we finalize the logo, I'll update it in the CNAB community assets repository.

![logo](https://raw.githubusercontent.com/deislabs/porter/master/docs/static/images/porter-logo.png)

**Comment by michelleN** [comment]
ah I love it!!!!! This is amazing yall!

**Comment by michelleN** [comment]
just one thing... do ya'll get thrown off by "porter" being in blue? If that's just me, then disregard. If it isn't just me... do we think having the porter logo be all three colors on the hat makes sense? cc/ @flynnduism @carolynvs

**Comment by carolynvs** [comment]
I think the porter text is the same purple as the triangle in the porter logo? We could take porter either in its own direction, or try to align with the cnab colors. What do you think of using the gray from the first sample logo in the OP issue instead?

I'm not sure yet what my opinion is which is why I'm still ok with the site being a total ripoff of the helm site. 😇
