### ISSUE TITLE
CLI: Add `porter bundle output(s)` list and show commands

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#445]
* add `porter bundle output(s) list [CLAIM] -o [table|json|yaml]` to list outputs for a bundle (bundle here is a claim in CNAB terms)
* add `porter bundle output show NAME [CLAIM]` to print the raw output value for the output named by `NAME` (associated with claim `CLAIM`)

**Comment by carolynvs** [comment]
I suggest using a flag to distinguish between the two names that need to be passed into the output show command (one for the output name and another for the claim name). Otherwise it is going to require people to look up in the helptext often to remember the order that they should be specified in and lead to wondering why porter can't find their claim when they wing it and get the order wrong.

```
porter bundle output show NAME --claim|-c CLAIM
```

The claim is always required, right? You used optional square brackets in the example, so I wanted to check if you had a trick for making it optional.

**Comment by vdice** [comment]
> The claim is always required, right? You used optional square brackets in the example, so I wanted to check if you had a trick for making it optional.

I was thinking we'd use our usual trick of attempting to infer the default claim name from current dir, as is done with `porter bundle show` -- but, to your point, yea, perhaps confusing/error prone to have a command with two args not attached to flags.  I'll implement w/ your suggestion of `--claim|-c CLAIM`

**Comment by carolynvs** [comment]
Nice! I like it. So it would be `porter bundle output show NAME [--claim|-c CLAIM]` 💯
