### ISSUE TITLE
Output commands are fragile due to marshaling directly from our structs

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#520]
I was working on loading outputs from dependencies into a running bundle and realized that because we save outputs to ~/.porter/outputs/CLAIM/OUTPUT as marshaled structs from the porter `Output` struct, it is sensitive to us changing that struct over time. If we change that struct in a release, then outputs created from previous releases may not unmarshal cleanly or without errors.

I'm wondering if we have another way to persist outputs, that would be more robust?

What if we stored just the value from the bundle's execution, and the looked up the bundle output definition from the claim? Or is there more data that we need to be persisting elsewhere in order to properly display an output again later? I'm not sure what drove the decision to save the entire `Output` struct from the porter.yaml so I'm tagging in @vdice for more background and context.

**Comment by vdice** [comment]
@carolynvs agreed, storing outputs as marshaled structs may present issues in the future.

We went this route so that the [print logic](https://github.com/deislabs/porter/blob/master/pkg/porter/outputs.go#L143-L181), say, on `porter bundle outputs list` could populate other pertinent info besides just the output value (output name, type, printing the path if output is sensitive, etc.)  If we want to continue to provide such info, but there is an alternate/better way to do so, let's do it.  If we decide we only really want to provide the output value, we can also remove the structured approach...

**Comment by carolynvs** [comment]
What do you think about using the marshaled bundle.json definition inside the claim, along with the output value that is also in the claim?

We can unmarshal the bundle.json and retrieve the properties from the outputs that we want: sensitive is going to be "writeOnly", type and name are straightforward and everything will be on the definition. The value is stored in the claim as well.

Those are all part of the Core 1.0 spec, and won't change without a major version bump which seems a bit more stable.

Thoughts?

**Comment by carolynvs** [comment]
If you think that our structs are just as stable as the Core Spec 1.0 structs in cnab-go, then it doesn't matter.

One more question is just to double check that this works the same for CNAB bundles (say made by duffle) and Porter bundles. Sensitive is specific to Porter so I wanted to check.

**Comment by vdice** [comment]
> What do you think about using the marshaled bundle.json definition inside the claim, along with the output value that is also in the claim?

Yea, this is probably the best way to go.  Output values were added to the claim in the spec after we implemented outputs in Porter.  Going this route would ideally simplify logic quite a bit!
