### ISSUE TITLE
Document how to test a mixin with multiple expected commands

### ISSUE THREAD

**Issue by donmstewart** [deislabs/porter#715]
## To Reproduce
1. Run `...`
2. Use this porter.yaml from this repository or gist
3. Run this porter command `...`

## Porter Command and Output
```
$ porter [e.g. install --param foo=bar --cred azure]
lots of output
```

## Version
Copy the output of `porter version` below

[e.g. porter v0.14.1-beta.2 (72dd5df)]

**Comment by donmstewart** [comment]
Please ignore fixed before finishing the ticket :)

**Comment by carolynvs** [comment]
MAGIC! 🎩✨ Let us know if there's a rough edge that needs to be fixed/documented.

**Comment by donmstewart** [comment]
Only documentation on the "\n" separation of Expected Results in the test cases.

The rest was muppetry on my part. :)

**Comment by carolynvs** [comment]
oh yeah we have like negative docs on how to test mixins... 😢 Let's fix that and start a new page that explains this part and go from there!

**Comment by carolynvs** [comment]
As you hit stuff like this, it would be very welcome for you to open issues, no matter how brief, calling out what would have helped, even if you've already figured it out. I'll follow behind and fill out the issue enough so that someone can tackle it.

I realize that we have a black hole of mixin developer docs and I'd like to fix that.

**Comment by donmstewart** [comment]
Sure thing not a problem.

**Comment by carolynvs** [comment]
@donmstewart I just opened a PR to add doc for this if you'd like to take a look. https://github.com/deislabs/porter/pull/717
