### ISSUE TITLE
Make the porter manifest available to the client for tag based bundle execution

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#801]
When we are working with a bundle that we pulled from a registry, we don't have access to the porter.yaml. It would be very helpful to know if it was a porter bundle and be able to take advantage of any porter specific features. For example, dependency overrides, "file" parameter types, etc.

Let's come up with how we'd like to figure out that a bundle was made by porter and get at the manifest.

1. Crack the invocation image and stuff it in the cache on pull
2. Stuff it in the custom metadata in the bundle.json
3. goat magic 🎩 ✨

**Comment by squillace** [comment]
Can you elaborate on "tag-based bundle execution"? The description just says it would be "helpful to know" but doesn't say what features/scenarios go with this helpfulness.

**Comment by brandonjbjelland** [comment]
Related problem but potentially the same root cause.

```bash
porter version
porter v0.23.0-beta.1-8-g2eb38e9 (2eb38e9)
```

I'm running into an issue in trying to pass parameters to dependent bundles as demonstrated in the [wordpress examples](https://github.com/deislabs/porter/blob/master/build/testdata/bundles/wordpress/porter.yaml#L9-L14). I cooked up [a repo with the repro case](https://github.com/brandonjbjelland/cnab-experiments/tree/master/dependency-params-bug) to flesh out the details clearly. This behavior is inconsistent with the CLI experience where parameters work exactly as expected:

```bash
$ porter install \
  --tag brandoconnor/cnab-exec-component:v0.3.0 \
  --param environment=steve # defaults to dev within the bundle
installing cnab-exec-component...
executing install action from cnab-exec-component (bundle instance: cnab-exec-component)
Testing variable IO within dependency
{
  "action": "install",
  "environment": "steve",
  "somearg": "foo"
}
execution completed successfully!
```

^ @squillace - I gather this is what's meant by a tag-based bundle execution. The issue I'm hitting is strictly a problem with executing as a dependency from within a parent bundle.

From my testing, a bundle invoking a dependency is unable to pass parameters at all - only the defaults defined within the child bundle apply. The issue I'm describing may or may not be separate of the core problem described here... though they're easily second-cousins.

```bash
$ porter install --param environment=prod
Executing dependency exec-child...
executing install action from cnab-exec-component (bundle instance: cnab-parent-component-exec-child)
Testing variable IO within dependency
{
  "action": "install",
  "environment": "dev",
  "somearg": "foo"
}
execution completed successfully!
installing cnab-parent-component...
executing install action from cnab-parent-component (bundle instance: cnab-parent-component)
Install Hello World
Hello World
execution completed successfully!
$ grep dependencies -A6 porter.yaml
dependencies:
  exec-child:
    tag: brandoconnor/cnab-exec-component:v0.3.0
    parameters:
      somearg: bar # huh?
      environment: steve # wut?
```

If you want a separate issue, let me know and I'll get to copy-pasta'ing. 🍝

**Comment by carolynvs** [comment]
@brandonjbjelland Yes, let's split this off into a separate bug that we can track. Thanks! I'm pumped that you are trying out dependencies. 💥
