### ISSUE TITLE
UX Enhancement: Place PORTER_MIXINS  up front in the default DockerFile

### ISSUE THREAD

**Issue by squillace** [deislabs/porter#841]
I propose that the default for PORTER_MIXINS in the default dockerfile is right after the FROM commands, always, _unless the Dockerfile.tmpl is used, and THEN the user controls it.

https://github.com/deislabs/porter/issues/707 gave us the ability to rebuild our bundles iteratively to test/debug without having to wait for complex mixins to download and optimize their portion of the Dockerfile. (And this without having to know what Porter is doing to create the Dockerfile in the first place unless you need to.) 

Yay! BUT:  

This is amazing, but it also requires the user to:
1. uncomment the Dockerfile.tmpl file
2. do the right thing. This is easy with respect to PORTER_MIXINS, which the docs call out. BUT it turns out that because the default `porter create` command leaves you with a Dockerfile.tmpl file with the following lines on the bottom:
`# Use the BUNDLE_DIR build argument to copy files into the bundle`
`# COPY . $BUNDLE_DIR`
you end up not knowing for a long time that you should go back and _uncomment the copy bundledir_ portion. Anger ensues.

I am unaware of any strong argument for NOT doing this, but surely I'm missing something.

**Comment by carolynvs** [comment]
Hey Ralph,

In the time since you created this issue, the default dockerfile template has changed to be an exact match for the dockerfile we use when you _don't_ have a dockerfile template at all. So you start customizing from a familiar starting point.

https://github.com/deislabs/porter/blob/master/pkg/templates/templates/create/Dockerfile.tmpl

I think this solves the pain point you raised and we can close the issue. If I'm wrong please reopen and we can hash it out more!
