### ISSUE TITLE
kubernetes mixin: allow portability across different base images

### ISSUE THREAD

**Issue by davidmontoyago** [deislabs/porter#844]
During an invocation image build, if the base image specified in `Dockerfile.tmpl` does not support `apt-get` the build process fails. In my case I'm looking to use an alpine image with Golang like [this](https://github.com/davidmontoyago/cnab-grpc-hello-world-svc/blob/master/Dockerfile.tmpl#L1).

```
Starting Invocation Image Build =======>
Error: unable to build CNAB invocation image: failed to stream docker build output: The command '/bin/sh -c apt-get update && apt-get install -y apt-transport-https curl && curl -o kubectl https://storage.googleapis.com/kubernetes-release/release/v1.15.5/bin/linux/amd64/kubectl && mv kubectl /usr/local/bin && chmod a+x /usr/local/bin/kubectl' returned a non-zero code: 127
```

WRT to kubectl, have y'all considered using the kubernetes API client instead of having the hard dependency on the kubectl binary? That way the mixin could be built as a (Golang?) lib for the target platform and avoid having to figure out which kubectl binary to use and how to install it.

Apologies in advance is this issue is unclear or out of place as I'm still trying to wrap my head around the porter workflow.

## To Reproduce
1. Use a linux base image that does not support apt-get.
2. Configure kubernetes mixin in porter.yaml.
3. `porter build`

## Expected behavior
Kubernetes mixin is cross platform and works seamlessly across diff base images.

## Version
`porter v0.22.0-beta.1 (8f3e429)`

**Comment by carolynvs** [comment]
I labeled this issue as a bug in our doc, because for the time being this is how the mixin is implemented and we should document that it needs a debian base image so that people don't trip up and expect any base image to work. I hope you didn't lose too much time on this! 😬 

Longer term, yes a solution for mixins that isn't tied to a particular architecture would be a nice to have. From a maintenance and feature perspective, reimplementing kubectl isn't viable, which is why all the mixins rely on getting the binary that we are shimming into the docker image. We don't have to use a package manager (e.g. apt) to do that however, or could be smarter about detecting which distro we are on.

In the short term, would using debian as a base image be an acceptable workaround? Or is there something that requires alpine in your scenario? Just asking so that I understand the use cases better.

**Comment by davidmontoyago** [comment]
Thanks for looking into this! Documentation of the base image limitation would indeed be helpful.

My main motivation for using alpine was the image size but debian should do it for now as I'm not taking it to prod (yet). Thanks again!

**Comment by carolynvs** [comment]
Yeah making the image size smaller is a concern, I'll take that as an extra vote for us to work on making them smaller in the future! 👍 

Thanks for the feedback!
