### ISSUE TITLE
Support for deleting the credentials

### ISSUE THREAD

**Issue by sowsan** [deislabs/porter#854]
What is the recommendation to delete the credentials created part of authoring the build?

**porter credentials** doesn't have an option to delete the existing credentials.

**Comment by vdice** [comment]
Good call.  We should add a `porter credentials delete NAME` command to delete a credential set.  

Currently, as credentials are still being stored locally (in the near future, we hope to add storage plugin support).  Therefore, the workaround is to delete them manually from the `credentials` sub-directory under Porter's home directory. (`${HOME}/.porter/credentials` on mac/linux.)

**Comment by sowsan** [comment]
Thank you @vdice . Also, I think I need a 101 on using the credentials. Any documentation on the sequence of using the credentials while authoring a bundle and what is happening behind the scene?

**Comment by carolynvs** [comment]
When you are authoring a bundle, you can define what credentials your bundle requires such as a github token, cloud provider username/password, etc. Then in your action's steps you can reference the credentials using porter's template language `{{ bundle.credentials.github_token }}`.

Credentials are injected when a bundle is executed (install/upgrade/uninstall/invoke). First a user creates a credentials set using `porter credentials generate`. This is a mapping that tells porter "given a name of a credential such as github_token, where can the value be found?", possible locations of a credential are: result of a command, environment value, file path, or hard coded value. The generate command walks you through all the credentials used by a bundle and where the values can be found.

Now when you execute the bundle you can pass the credential set to the command use `--cred` or `-c` flag, e.g. `porter install --cred github`. Before the bundle is executed, porter users the credential set's mappings to retrieve the credential values and then inject them into the bundle's execution environment, e.g. the docker container, as environment variables.

Inside the bundle's execution environment Porter looks for those environment variables that represent the credentials and replaces the template placeholders like `{{ bundle.credentials.github_token }}` with the actual credential value before executing the step.

Once the bundle finishes executing, the credentials are NOT recorded in the bundle instance (claim). Parameters are recorded there so that you can view them later using `porter instances show NAME --output json`.

**Comment by carolynvs** [comment]
IOU one new page in the docs with my previous comment copy/pasted into it. 📒

**Comment by sowsan** [comment]
Great thank you so much :)

**Comment by carolynvs** [comment]
```
$ porter credentials delete NAME
```

* NAME is the name of the credential set.
* If the credential set doesn't exist, print a debug message, and return successfully.
* Do not prompt for confirmation.
* Add the new command to https://github.com/deislabs/porter/blob/master/cmd/porter/credentials.go and implement it in https://github.com/deislabs/porter/blob/master/pkg/porter/credentials.go
* Add a test to https://github.com/deislabs/porter/blob/master/pkg/porter/credentials_test.go to confirm the file was removed from `/root/.porter/credentials`
